version: '3'
services:
  main:
    container_name: nodebase_main
    build: .
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    restart: always
    environment:
      NVM_DIR: '/root/.nvm'
    networks:
      docknet:
        ipv4_address: 172.20.0.2
    command: >
      bash -c "
        . /root/.bashrc
        pm2-runtime start ecosystem.config.js
      "
    ports:
      - 3000:3000
      - 9229:9229
  mongo:
    container_name: nodebase_mongo
    image: mongo:4.0
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    networks:
      docknet:
        ipv4_address: 172.20.0.3
networks:
  docknet:
      driver: bridge
      ipam:
        config:
          - subnet: 172.20.0.0/24